name: Build Binder

on:
    workflow_dispatch:

jobs:
    build-binder:
        runs-on: ubuntu-latest
        continue-on-error: true
        strategy:
          fail-fast: false
          matrix:
            binder-provider: ["gke"]

        steps:
            - name: Hello
              run: echo "hello ${{ matrix.binder-provider }}" | tee output-${{ matrix.binder-provider }}.txt
            - name: Assert build succeeded
              run: |
                [ -s output-${{ matrix.binder-provider }}.txt ] || exit 1
                if grep -q "\"phase\": \"failed\"" output-${{ matrix.binder-provider }}.txt; then
                    if grep -q "\"phase\": \"built\"" output-${{ matrix.binder-provider }}.txt; then
                        echo "::warning ::Failed to launch, but build still succeeded"
                        exit 0
                    else
                        echo "::error ::Failed to launch, failed to build"
                        exit 1
                    end
                end
                if grep -q "\"phase\": \"ready\"" output-${{ matrix.binder-provider }}.txt; then
                    exit 0
                else
                    echo "::error ::Failed to launch, not sure why"
                    exit 1
                end
                
            - name: Upload log file
              if: ${{ always() }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.binder-provider }} Build log
                  path: output-${{ matrix.binder-provider }}.txt
